name: Blockhouse
favicon: null
layout_spectrum: 0.5472727303858846
typography_spectrum: 0.396933660376817
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7422152787912637
  lightness: 0.024943798780441284
  saturation: 0.7436939470935613
  rhythmicContrast: 0.6088409591466188
purpose: []
