name: Blockhouse
favicon: null
layout_spectrum: 0.75169
typography_spectrum: 0.13175
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4ede7'
    - '#a3a3c1'
    - '#394e62'
    - '#7688b5'
    - '#0e1412'
  brandStrength: 0.6875
  lightness: 0.125
  saturation: 0.75
  rhythmicContrast: 1
purpose: []
